# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '**.yml'
      - '**/**.yml'
  
pool:
  vmImage: ubuntu-latest

variables:
  - group: Deployment group

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureStaticWebApp@0
  displayName: Deploy to static web app
  inputs:
    app_location: '/'
    skip_api_build: true
    output_location: "wwwroot"
    azure_static_web_apps_api_token: $(deployment_token_static)
